server.port=8083
spring.application.name=order-notification-service
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.order.notification=DEBUG

resilience4j.circuitbreaker.instances.notificationDb.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationDb.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.notificationDb.sliding-window-size=5
resilience4j.circuitbreaker.instances.notificationDb.wait-duration-in-open-state=15s

resilience4j.retry.instances.notificationDbRetry.max-attempts=3
resilience4j.retry.instances.notificationDbRetry.wait-duration=2s